### PR TITLE
C objects feature

### PR DESCRIPTION
**Pull request by bunny351**
Here another variant, that uses csc's "-feature" option to distinguish between a build that uses the system-wide installed sqlite3 or the included one. Note that this is much cleaner and leaves the choice to the user.

### CODE REVIEW

**Comment by ursetto** [comment]
I kinda like this one the best. I didn't even know you could `cond-expand` in a `.egg` file.

Having the script decide which sqlite version to use was always a little too cute. It was intended to transparently guarantee a minimum amount of sqlite functionality for egg authors, while letting the user use a (more secure) later version if installed. This meant I didn't have to update the egg constantly with new sqlite versions. But, it's also a pain in retrospect. Let me think about this for a bit.

**Comment by wasamasa** [comment]
I've tried out this patch now, to use the bundled SQLite `-pthread` must be passed in the linker options. No such change needed for the system version.

**Comment by ursetto** [comment]
@wasamasa Looks like the `FTS3` and `THREADSAFE=0` options were dropped in this patch (the latter causes the `-pthread` issue). I imagine I can add them back in.

@bunny351 It looks like this patch flips the build behavior on Windows -- in the original code the internal library is always built, in the new code the external library is always used. I have no good way to test on / support Windows so I don't mind much either way, but I wanted to confirm this was intentional. When @sjamaan rewrote the build for Chicken 5 this behavior changed as well, so consistency is not too important.

**Comment by ursetto** [comment]
I restored the pthreads/FTS options and renamed the feature to align with Chicken 4 (it was removed for Chicken 5.0).

I also reenabled the internal build for Windows. chicken-sqlite3 was being built internally anyway for Windows, so if internal builds fail then that will too. I skipped the `.bat` file shim for external builds. If this totally breaks Windows, let me know.

**Comment by wasamasa** [comment]
I guess this means #4 and #5 can be closed. I'll try it on Windows soonish.

edit: Works on Windows as expected.

**Pull request merged**
