### PR TITLE
Allow loading extensions from Scheme code.

### PR DESCRIPTION
**Pull request by CMB**
This only enables the C API for loading extensions, not the
load_extension SQL function.
The function load-extension! is exposed to Scheme..

### CODE REVIEW

**Comment by ursetto** [comment]
Thanks, I think this looks ok.  Will try to test and merge soon.

**Comment by ursetto** [comment]
Added various fixes which were necessary to compile. Please test on your system. I have tested on OS X with Chicken 4.12 and 5.2.

**Comment by CMB** [comment]
Tests pass on both Linux and FreeBSD 13.0.
Thanks.

**Comment by ursetto** [comment]
This is available in 0.10.0. Thank you.

**Pull request merged**
