### PR TITLE
Fix version detection and tests

### PR DESCRIPTION
**Pull request by sjamaan**
The commits should be pretty self-explanatory.

### CODE REVIEW

**Comment by ursetto** [comment]
Would you like me to release a new version or are you still working on it?

**Comment by sjamaan** [comment]
Please make a new release

**Comment by ursetto** [comment]
There's an issue with this patch: if we use the system version of sqlite3, we may not be able to compile the shell against it. It fails to build on my system.

1) shell.c will be older, and the API may have changed in the new version (theoretical problem)

2) On macosx the "sqlite3_load_extension" API is disabled (removed) because macos is silly. The shell.c assumes the API is available; compilation against the system sqlite3 fails.

2 possible ways to fix this:

1) update sqlite3 version in egg, forcing macosx to use a newer version

2) symlink / copy system sqlite3 shell to chicken-sqlite3.

I'm thinking the shell change should be backed out. The chicken-sqlite3 shell is provided as a convenience to the user, in case they don't have a system sqlite3 shell, but users should not rely on its existence. It's just for debugging.

**Comment by sjamaan** [comment]
I had to add this change because C5 chicken-install does not currently support conditional build/installation of components.

Copying or symlinking the system shell sounds like it would easily fail.

**Comment by ursetto** [comment]
I have a proposed fix that seems "ok" if not perfect. Let me send you a PR so you can review.

**Comment by ursetto** [comment]
Check out PR #2.

Can't figure out the proper way to tag you on that, I'm not good at this.

**Pull request merged**
